[package]
name    = "hotp"
version = "0.1.0"
authors = ["Eric Bailey <eric@ericb.me>"]

[dependencies]
libc        = "0.2.14"
rust-crypto = "^0.2"

[lib]
name = "hotp"
# crate_type = ["staticlib"]
crate_type = ["dylib"]
